### ISSUE TITLE
04 - 01 - GET https://intro-to.api.com/knowledge

### ISSUE THREAD

**Issue by AbeEveland** [AbeEveland/assignments#14]
In this project, you will practice accessing an API. You'll see how an API request is made, and see how data is returned from an API

## Objectives

- Demonstrate usage of APIs
- Understand how an API request is sent.
- Understand the request and response for an API.

### Explorer Mode

- [] Choose one of the APIs from
  [this list](https://github.com/public-apis/public-apis) that does not request
  "AUTH" (Authorization) since an API that requires authorization is a little
  more difficult to use when first learning. I have also selected some sample
  APIs that will be good choices:

| API                                                      | Documentation                                  |
| -------------------------------------------------------- | ---------------------------------------------- |
| Dogs                                                     | https://dog.ceo/dog-api/                       |
| Studio Ghibli https://ghibliapi.herokuapp.com/#tag/Films |
| Open Brewery                                             | https://www.openbrewerydb.org/                 |
| Recipes                                                  | http://www.recipepuppy.com/about/api/          |
| Deck of Cards!                                           | http://deckofcardsapi.com/                     |
| Geocode                                                  | https://geocode.xyz/api                        |
| Jobs                                                     | https://jobs.github.com/api                    |
| Lyrics                                                   | https://lyricsovh.docs.apiary.io/#reference    |
| Quotes                                                   | https://pprathameshmore.github.io/QuoteGarden/ |
| SpaceX                                                   | https://docs.spacexdata.com/?version=latest    |
| Jokes                                                    | https://github.com/15Dkatz/official_joke_api   |

- [ ] After choosing your API **read** the documentation.
- [ ] Use the `Insomnia` tool to make a few queries of the API.
- [ ] Capture screenshots from `Insomnia` showing your request and the response
      output.
- [ ] Attach those screenshots to your homework assignment.
- [ ] For one response, show a screenshot with the "Header" tab displayed.
- [ ] For this response, find a few headers and describe what they do. NOTE: If the header starts with `X-` it is a _custom_ header and likely is documented by your API. Other headers are more standard and can be google searched.

## Adventure Mode

Read the documentation on this API: https://one-list-api.herokuapp.com/

Choose your access token from your first and last name. For example `jane-doe`
or `ron-swanson`.

- [ ] Use `Insomnia` to insert 6 items in the list associated with your access token. Attach screenshots of the request and results screen.
- [ ] Use `Insomnia` to mark 2 of these items complete. Attach screenshots of the request and result screen.
- [ ] Use `Insomnia` to delete 1 of the non-complete items. Attach screenshots of the request and result screen.

## Epic Mode

- [ ] Investigate using C#'s `HttpClient` class to make requests to any of the APIs you used in Adventure mode.
- [ ] Create a console app that makes requests and prints the results. Submit the URL to the Github repository of this console app.

**Comment by AbeEveland** [comment]
Content-Type: application/json; charset=utf-8  : This says that the body of the response will be JSON data, and that the character representation will be utf-8.

Vary: Accept-Encoding : this tells the server if your browser can accept compressed output

X-Powered-By: Express: This is the technology supporting the web application.

Access-Control-Allow-Origin: * : specifying which websites can participate.

ETag: W/"5dc-DkWQk60/n4itPTHX4o4ead49d8o" : An identifier for a specific version of a resource. 

X-Cloud-Trace-Context: 5c6d2bf2b0450096938eefecf269785b : helps identify the current request

Date: Wed, 03 Jun 2020 19:35:46 GMT: date and time at which the message was originated

Server: Google Frontend:  a name for the server

Content-Length: 1500
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

![Screenshot (20)](https://user-images.githubusercontent.com/63511547/83685542-d5ee0c00-a5b6-11ea-87c7-335d0f3387d5.png)
![Screenshot (21)](https://user-images.githubusercontent.com/63511547/83685554-dab2c000-a5b6-11ea-9aed-569fc3f129f2.png)
![Screenshot (22)](https://user-images.githubusercontent.com/63511547/83685561-dc7c8380-a5b6-11ea-9387-e26371ee3199.png)
![Screenshot (23)](https://user-images.githubusercontent.com/63511547/83685574-df777400-a5b6-11ea-8960-30117cfb473f.png)

**Comment by AbeEveland** [comment]
Your homework **04 - 01 - GET https://intro-to.api.com/knowledge** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6653a5b4c8e877384d759556a53bfc97521ca49f/giphy-17.gif)
> &ldquo;Well done!&rdquo;

**Comment by gstark** [comment]
Very nice!
