### ISSUE TITLE
06 - 02 - Iteration in JavaScript

### ISSUE THREAD

**Issue by AbeEveland** [AbeEveland/assignments#23]
## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `hub clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
8. Open `src/functions.test.js` and work on functions until tests pass.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing

## Epic Mode

- Using the `forEach` looping method and no other looping or enumeration helper, write your **own version** of the following methods, except name yours `_map`,
  `_filter`, etc.
  - `map`
  - `filter`
  - `reduce`
  - `every`
  - `some`
- Write some example usage of your new methods to demonstrate that they work

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions
might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by AbeEveland** [comment]
https://github.com/AbeEveland/js-iteration

**Comment by gstark** [comment]
I don't think you committed your work. I don't see *your* code:

![js-iteration 2020-06-25 08-54-43](https://user-images.githubusercontent.com/2607/85723760-8d130a00-b6c1-11ea-9a32-556d636ab5d8.png)

**Comment by AbeEveland** [comment]
Your homework **06 - 02 - Iteration in JavaScript** was marked: **Unacceptable**


![I'm just gonna...](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--354ad6ba2ab2a53888555f9ec77d2db94e87586c/nope.gif)
> &ldquo;I'm just gonna...&rdquo;

**Comment by AbeEveland** [comment]
https://github.com/AbeEveland/js-iteration

**Comment by AbeEveland** [comment]
This should have my code

**Comment by AbeEveland** [comment]
Your homework **06 - 02 - Iteration in JavaScript** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5aaf4fb8aebc193771c4dd6c9823d8f6300ba70b/giphy-7.gif)
> &ldquo;Well done!&rdquo;

**Comment by gstark** [comment]
Awesome! Thanks! Great work!
