### ISSUE TITLE
02-03 Jurassic Park - 

### ISSUE THREAD

**Issue by AbeEveland** [AbeEveland/assignments#8]
In this assignment, you will be creating a console application that manages a zoo
full of dinosaurs.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.

## Requirements

- Create a console application that manages the dinosaurs in your zoo.

### Explorer Mode

- [ ] Create a class to represent your dinosaurs. The class should have the following properties

  - [ ] `Name`
  - [ ] `DietType` - This will be "carnivore" or "herbivore"
  - [ ] `WhenAcquired` - This will default to the current time when the
        dinosaur is created
  - [ ] `Weight` - How heavy the dinosaur is in pounds.
  - [ ] `EnclosureNumber` - the number of the pen the dinosaur is currently in

- [ ] Add a method `Description` to your class to print out a description of the dinosaur to include all of its properties. Create an output format of your choosing.
- [ ] Your dinosaurs will be stored in a `List<Dinosaur>`.
- [ ] When the console application runs, it should let the user choose one of the following actions:
  - [ ] `View`
    - This command will show the all the dinosaurs in the list, ordered by `WhenAcquired`
  - [ ] `Add`
    - This command will let the user type in the information for a dinosaur and add it to the list
  - [ ] `Remove`
    - This command will prompt the user for a dinosaur name then find and delete the dinosaur with that name.
  - [ ] `Transfer`
    - This command will prompt the user for a dinosaur name and a new `EnclosureNumber` and update that dino's information.
  - [ ] `Summary`
    - [ ] This command will display the number of carnivores and the number of herbivores.
  - [ ] `Quit`
    - [ ] This will stop the program

### Adventure Mode

- [ ] Add an option to view the Dinosaurs acquired after a given date (to be given by the user).
- [ ] Add an option to view all the Dinosaurs in a given enclosure number.

### Epic Mode

- [ ] Learn how to read and write from a file. At the start of the program load all the dinosaurs from a file. When the program ends write out all the dinosaurs to the same file.

**Comment by AbeEveland** [comment]
https://github.com/AbeEveland/jurassicpark2

**Comment by AbeEveland** [comment]
The completed home work is in jurassicpark2

**Comment by AbeEveland** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e11f1f3541d668540d195fe7adcb68fd773344b8/giphy-12.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/77)**__

**Comment by gstark** [comment]
Good job! Here is some minor feedback.

Each of these, `name`, `diettype`, `whenaquired` should be `CapitalCase` like this `Name`, `DietType`, `WhenAquired` -- https://github.com/AbeEveland/jurassicpark2/blob/master/Program.cs#L34

This should be named `Description` -- https://github.com/AbeEveland/jurassicpark2/blob/master/Program.cs#L40

The weight should be an integer. You can format it to say `lbs` on *output*. Store the information as an integer, but every time you Console.WriteLine it, use `$"The weight is {dino.Weight} lbs"` or something similar -- https://github.com/AbeEveland/jurassicpark2/blob/master/Program.cs#L37

This should be `while(true)` https://github.com/AbeEveland/jurassicpark2/blob/master/Program.cs#L107

This is debugging code, remove: https://github.com/AbeEveland/jurassicpark2/blob/master/Program.cs#L110-L119
